### ISSUE TITLE
json: cannot unmarshal string into Go struct field lakeManifest.version of type int 

### ISSUE THREAD

**Issue by zhouliang-yu** [leanprover-community/mathlib4#14222]
Hi， 
When I was trying to build the mathlib4 for lean, I met the following issue 

```
2024/06/28 17:15:05 got dotElanBaseDir `/root/.elan`
2024/06/28 17:15:05 flag.Parse: got command = ``, version = ``
Found latest version: v0.1.12
run `glean -update` to update
panic: error parsing lake manifest `lake-manifest.json`, json: cannot unmarshal string into Go struct field lakeManifest.version of type int

goroutine 1 [running]:
github.com/alissa-tung/glean/glean.readAndParse({0x7fffd64201fd, 0x12})
        /Users/alissa/pod/glean/glean/lake.go:86 +0x1d4
github.com/alissa-tung/glean/glean.LakeSyncPackages()
        /Users/alissa/pod/glean/glean/lake.go:97 +0x30
main.main()
        /Users/alissa/pod/glean/main.go:25 +0x6f
```

And the shell script I used to build is:
```
glean -lake-manifest-path lake-manifest.json 
```

Does Anyone met the same error, or has any clue to solve the problem?

**Comment by eric-wieser** [comment]
`glean` is not part of mathlib, I suggest you report this at https://github.com/alissa-tung/glean

**Comment by eric-wieser** [comment]
I think https://github.com/alissa-tung/glean/pull/14 might have fixed this anyway.
